+// AI Tools Data
+const categories = [
+    {
+        id: 'writing',
+        name: 'Writing & Content',
+        icon: 'fas fa-pen-fancy',
+        description: 'AI-powered writing assistants and content generators'
+    },
+    {
+        id: 'image',
+        name: 'Image Generation',
+        icon: 'fas fa-image',
+        description: 'Create stunning visuals with AI'
+    },
+    {
+        id: 'code',
+        name: 'Code & Development',
+        icon: 'fas fa-code',
+        description: 'AI coding assistants and development tools'
+    },
+    {
+        id: 'voice',
+        name: 'Voice & Audio',
+        icon: 'fas fa-microphone',
+        description: 'Speech synthesis and audio processing'
+    },
+    {
+        id: 'video',
+        name: 'Video & Animation',
+        icon: 'fas fa-video',
+        description: 'AI-powered video creation and editing'
+    },
+    {
+        id: 'automation',
+        name: 'Automation',
+        icon: 'fas fa-robot',
+        description: 'Workflow automation and process optimization'
+    },
+    {
+        id: 'design',
+        name: 'Design & UI/UX',
+        icon: 'fas fa-palette',
+        description: 'AI design tools and creative assistance'
+    },
+    {
+        id: 'data',
+        name: 'Data & Analytics',
+        icon: 'fas fa-chart-line',
+        description: 'Data analysis and business intelligence'
+    },
+    {
+        id: 'productivity',
+        name: 'Productivity',
+        icon: 'fas fa-tasks',
+        description: 'Boost productivity with AI assistants'
+    },
+    {
+        id: 'marketing',
+        name: 'Marketing & SEO',
+        icon: 'fas fa-bullhorn',
+        description: 'AI marketing tools and optimization'
+    },
+    {
+        id: 'research',
+        name: 'Research & Knowledge',
+        icon: 'fas fa-search',
+        description: 'AI-powered research and information gathering'
+    },
+    {
+        id: 'education',
+        name: 'Education & Learning',
+        icon: 'fas fa-graduation-cap',
+        description: 'AI tutors and educational tools'
+    }
+];
+
+const aiTools = [
+    // Writing & Content
+    {
+        id: 1,
+        name: 'ChatGPT',
+        description: 'Advanced conversational AI that can help with writing, analysis, coding, and creative tasks. Your AI assistant for almost anything.',
+        category: 'writing',
+        pricing: 'Freemium',
+        features: ['Conversational AI', 'Content generation', 'Code assistance', 'Analysis'],
+        websiteUrl: 'https://chat.openai.com',
+        logoUrl: '🤖',
+        rating: 4.8,
+        tags: ['chatbot', 'content generation', 'analysis', 'coding'],
+        trendingRank: 1,
+        upvotes: 15420,
+        uses: 2500000
+    },
+    {
+        id: 2,
+        name: 'Jasper AI',
+        description: 'AI writing assistant that helps create high-quality content for blogs, ads, emails, and websites in minutes.',
+        category: 'writing',
+        pricing: 'Paid',
+        features: ['Blog writing', 'Ad copy', 'Email marketing', 'Content templates'],
+        websiteUrl: 'https://jasper.ai',
+        logoUrl: '✍️',
+        rating: 4.6,
+        tags: ['writing', 'marketing', 'content creation', 'copywriting'],
+        trendingRank: null,
+        upvotes: 8920,
+        uses: 450000
+    },
+    {
+        id: 3,
+        name: 'Copy.ai',
+        description: 'AI-powered copywriter that helps you create compelling content for marketing, sales, and everyday business needs.',
+        category: 'writing',
+        pricing: 'Freemium',
+        features: ['Sales copy', 'Social media', 'Product descriptions', 'Email sequences'],
+        websiteUrl: 'https://copy.ai',
+        logoUrl: '📝',
+        rating: 4.5,
+        tags: ['copywriting', 'marketing', 'sales', 'social media'],
+        trendingRank: null,
+        upvotes: 7650,
+        uses: 380000
+    },
+    {
+        id: 4,
+        name: 'Grammarly',
+        description: 'AI writing assistant that helps improve your writing with grammar checking, tone detection, and writing suggestions.',
+        category: 'writing',
+        pricing: 'Freemium',
+        features: ['Grammar checking', 'Tone detection', 'Plagiarism detection', 'Writing suggestions'],
+        websiteUrl: 'https://grammarly.com',
+        logoUrl: '📚',
+        rating: 4.7,
+        tags: ['grammar', 'editing', 'writing improvement', 'proofreading'],
+        trendingRank: null,
+        upvotes: 12340,
+        uses: 1200000
+    },
+    {
+        id: 5,
+        name: 'Notion AI',
+        description: 'AI writing assistant built into Notion that helps brainstorm, edit, and create content within your workspace.',
+        category: 'writing',
+        pricing: 'Freemium',
+        features: ['Brainstorming', 'Content editing', 'Summarization', 'Translation'],
+        websiteUrl: 'https://notion.so/product/ai',
+        logoUrl: '📄',
+        rating: 4.4,
+        tags: ['productivity', 'workspace', 'editing', 'brainstorming'],
+        trendingRank: null,
+        upvotes: 5680,
+        uses: 290000
+    },
+
+    // Image Generation
+    {
+        id: 6,
+        name: 'DALL·E 2',
+        description: 'Create realistic images and art from text descriptions. Generate, edit, and create variations of images using AI.',
+        category: 'image',
+        pricing: 'Freemium',
+        features: ['Text-to-image', 'Image editing', 'Variations', 'Inpainting'],
+        websiteUrl: 'https://openai.com/dall-e-2',
+        logoUrl: '🎨',
+        rating: 4.6,
+        tags: ['text-to-image', 'art generation', 'creative', 'editing'],
+        trendingRank: 2,
+        upvotes: 11250,
+        uses: 850000
+    },
+    {
+        id: 7,
+        name: 'Midjourney',
+        description: 'AI image generator that creates stunning artwork from text prompts. Known for its artistic and creative outputs.',
+        category: 'image',
+        pricing: 'Paid',
+        features: ['Text-to-image', 'Artistic styles', 'High quality', 'Community gallery'],
+        websiteUrl: 'https://midjourney.com',
+        logoUrl: '🌟',
+        rating: 4.8,
+        tags: ['art generation', 'creative', 'artistic', 'text-to-image'],
+        trendingRank: 3,
+        upvotes: 13400,
+        uses: 720000
+    },
+    {
+        id: 8,
+        name: 'Stable Diffusion',
+        description: 'Open-source AI image generator that creates detailed images from text descriptions. Free and customizable.',
+        category: 'image',
+        pricing: 'Free',
+        features: ['Open source', 'Text-to-image', 'Customizable', 'Local installation'],
+        websiteUrl: 'https://stability.ai/stable-diffusion',
+        logoUrl: '🔄',
+        rating: 4.5,
+        tags: ['open source', 'text-to-image', 'free', 'customizable'],
+        trendingRank: null,
+        upvotes: 9870,
+        uses: 650000
+    },
+    {
+        id: 9,
+        name: 'Adobe Firefly',
+        description: 'AI-powered creative tools integrated into Adobe Creative Suite for generating images, text effects, and more.',
+        category: 'image',
+        pricing: 'Freemium',
+        features: ['Creative suite integration', 'Text effects', 'Image generation', 'Style transfer'],
+        websiteUrl: 'https://firefly.adobe.com',
+        logoUrl: '🔥',
+        rating: 4.3,
+        tags: ['adobe', 'creative suite', 'text effects', 'professional'],
+        trendingRank: null,
+        upvotes: 6420,
+        uses: 340000
+    },
+    {
+        id: 10,
+        name: 'Leonardo AI',
+        description: 'AI art generator focused on game assets, concept art, and creative projects with fine-tuned models.',
+        category: 'image',
+        pricing: 'Freemium',
+        features: ['Game assets', 'Concept art', 'Fine-tuned models', 'Canvas editor'],
+        websiteUrl: 'https://leonardo.ai',
+        logoUrl: '🎮',
+        rating: 4.4,
+        tags: ['game assets', 'concept art', 'creative', 'fine-tuned'],
+        trendingRank: null,
+        upvotes: 4230,
+        uses: 180000
+    },
+
+    // Code & Development
+    {
+        id: 11,
+        name: 'GitHub Copilot',
+        description: 'AI pair programmer that helps you write code faster with intelligent code completions and suggestions.',
+        category: 'code',
+        pricing: 'Paid',
+        features: ['Code completion', 'Multi-language support', 'IDE integration', 'Code suggestions'],
+        websiteUrl: 'https://github.com/features/copilot',
+        logoUrl: '🐙',
+        rating: 4.7,
+        tags: ['coding', 'IDE', 'completion', 'github'],
+        trendingRank: 4,
+        upvotes: 14200,
+        uses: 950000
+    },
+    {
+        id: 12,
+        name: 'Cursor',
+        description: 'AI-first code editor that helps you build software faster with AI-powered editing and chat.',
+        category: 'code',
+        pricing: 'Freemium',
+        features: ['AI editing', 'Code chat', 'Codebase understanding', 'Refactoring'],
+        websiteUrl: 'https://cursor.sh',
+        logoUrl: '⚡',
+        rating: 4.6,
+        tags: ['code editor', 'ai chat', 'refactoring', 'productivity'],
+        trendingRank: 5,
+        upvotes: 8760,
+        uses: 420000
+    },
+    {
+        id: 13,
+        name: 'Replit Ghostwriter',
+        description: 'AI assistant built into Replit that helps with code completion, explanation, and debugging.',
+        category: 'code',
+        pricing: 'Freemium',
+        features: ['Code completion', 'Code explanation', 'Debugging', 'Online IDE'],
+        websiteUrl: 'https://replit.com/ai',
+        logoUrl: '👻',
+        rating: 4.3,
+        tags: ['online IDE', 'debugging', 'explanation', 'completion'],
+        trendingRank: null,
+        upvotes: 5340,
+        uses: 280000
+    },
+    {
+        id: 14,
+        name: 'Tabnine',
+        description: 'AI code assistant that provides intelligent code completions for multiple programming languages and IDEs.',
+        category: 'code',
+        pricing: 'Freemium',
+        features: ['Multi-language', 'IDE integration', 'Team learning', 'Local models'],
+        websiteUrl: 'https://tabnine.com',
+        logoUrl: '🔀',
+        rating: 4.4,
+        tags: ['completion', 'multi-language', 'IDE', 'team'],
+        trendingRank: null,
+        upvotes: 6780,
+        uses: 380000
+    },
+    {
+        id: 15,
+        name: 'CodeT5',
+        description: 'Open-source AI model for code understanding and generation, supporting multiple programming tasks.',
+        category: 'code',
+        pricing: 'Free',
+        features: ['Open source', 'Code generation', 'Code understanding', 'Multi-task'],
+        websiteUrl: 'https://github.com/salesforce/CodeT5',
+        logoUrl: '🤖',
+        rating: 4.2,
+        tags: ['open source', 'generation', 'understanding', 'research'],
+        trendingRank: null,
+        upvotes: 3450,
+        uses: 120000
+    },
+
+    // Voice & Audio
+    {
+        id: 16,
+        name: 'ElevenLabs',
+        description: 'AI voice generator that creates realistic and versatile AI speech in any voice and style.',
+        category: 'voice',
+        pricing: 'Freemium',
+        features: ['Voice cloning', 'Text-to-speech', 'Multiple languages', 'Realistic voices'],
+        websiteUrl: 'https://elevenlabs.io',
+        logoUrl: '🎤',
+        rating: 4.7,
+        tags: ['voice cloning', 'text-to-speech', 'realistic', 'multilingual'],
+        trendingRank: 6,
+        upvotes: 9840,
+        uses: 520000
+    },
+    {
+        id: 17,
+        name: 'Murf AI',
+        description: 'AI voice generator for creating professional voiceovers with 120+ voices in 20+ languages.',
+        category: 'voice',
+        pricing: 'Freemium',
+        features: ['Professional voices', 'Multiple languages', 'Voice editing', 'Commercial use'],
+        websiteUrl: 'https://murf.ai',
+        logoUrl: '🎙️',
+        rating: 4.5,
+        tags: ['voiceover', 'professional', 'commercial', 'editing'],
+        trendingRank: null,
+        upvotes: 6230,
+        uses: 290000
+    },
+    {
+        id: 18,
+        name: 'Speechify',
+        description: 'AI text-to-speech tool that converts any text into natural-sounding speech for better accessibility.',
+        category: 'voice',
+        pricing: 'Freemium',
+        features: ['Text-to-speech', 'Natural voices', 'Speed control', 'OCR support'],
+        websiteUrl: 'https://speechify.com',
+        logoUrl: '📢',
+        rating: 4.6,
+        tags: ['accessibility', 'natural speech', 'OCR', 'reading'],
+        trendingRank: null,
+        upvotes: 8120,
+        uses: 450000
+    },
+    {
+        id: 19,
+        name: 'Descript',
+        description: 'AI-powered audio and video editing tool with transcription, voice cloning, and editing features.',
+        category: 'voice',
+        pricing: 'Freemium',
+        features: ['Audio editing', 'Transcription', 'Voice cloning', 'Video editing'],
+        websiteUrl: 'https://descript.com',
+        logoUrl: '🎬',
+        rating: 4.4,
+        tags: ['audio editing', 'transcription', 'video', 'overdub'],
+        trendingRank: null,
+        upvotes: 5670,
+        uses: 240000
+    },
+    {
+        id: 20,
+        name: 'AIVA',
+        description: 'AI music composition assistant that creates original music for various projects and styles.',
+        category: 'voice',
+        pricing: 'Freemium',
+        features: ['Music composition', 'Multiple genres', 'Original music', 'Royalty-free'],
+        websiteUrl: 'https://aiva.ai',
+        logoUrl: '🎵',
+        rating: 4.3,
+        tags: ['music composition', 'original', 'royalty-free', 'genres'],
+        trendingRank: null,
+        upvotes: 4120,
+        uses: 150000
+    },
+
+    // Video & Animation
+    {
+        id: 21,
+        name: 'RunwayML',
+        description: 'AI-powered creative suite for video editing, generation, and visual effects with cutting-edge AI models.',
+        category: 'video',
+        pricing: 'Freemium',
+        features: ['Video generation', 'AI effects', 'Green screen', 'Style transfer'],
+        websiteUrl: 'https://runwayml.com',
+        logoUrl: '🎭',
+        rating: 4.5,
+        tags: ['video generation', 'effects', 'creative', 'editing'],
+        trendingRank: 7,
+        upvotes: 7890,
+        uses: 380000
+    },
+    {
+        id: 22,
+        name: 'Synthesia',
+        description: 'AI video platform that creates professional videos with AI avatars speaking in multiple languages.',
+        category: 'video',
+        pricing: 'Paid',
+        features: ['AI avatars', 'Multiple languages', 'Professional videos', 'Custom avatars'],
+        websiteUrl: 'https://synthesia.io',
+        logoUrl: '👤',
+        rating: 4.4,
+        tags: ['avatars', 'multilingual', 'professional', 'presentation'],
+        trendingRank: null,
+        upvotes: 6540,
+        uses: 320000
+    },
+    {
+        id: 23,
+        name: 'Pika Labs',
+        description: 'AI video generator that transforms text and images into dynamic video content.',
+        category: 'video',
+        pricing: 'Freemium',
+        features: ['Text-to-video', 'Image-to-video', 'Dynamic content', 'Creative effects'],
+        websiteUrl: 'https://pika.art',
+        logoUrl: '⚡',
+        rating: 4.3,
+        tags: ['text-to-video', 'image-to-video', 'dynamic', 'creative'],
+        trendingRank: 8,
+        upvotes: 5230,
+        uses: 210000
+    },
+    {
+        id: 24,
+        name: 'Loom AI',
+        description: 'AI-enhanced screen recording with automatic transcription, summaries, and video editing features.',
+        category: 'video',
+        pricing: 'Freemium',
+        features: ['Screen recording', 'Auto transcription', 'Summaries', 'Easy sharing'],
+        websiteUrl: 'https://loom.com',
+        logoUrl: '📹',
+        rating: 4.6,
+        tags: ['screen recording', 'transcription', 'sharing', 'summaries'],
+        trendingRank: null,
+        upvotes: 8940,
+        uses: 560000
+    },
+    {
+        id: 25,
+        name: 'Pictory',
+        description: 'AI video creator that turns long-form content into short, shareable videos automatically.',
+        category: 'video',
+        pricing: 'Freemium',
+        features: ['Content repurposing', 'Auto highlights', 'Video summaries', 'Social media'],
+        websiteUrl: 'https://pictory.ai',
+        logoUrl: '📽️',
+        rating: 4.2,
+        tags: ['repurposing', 'highlights', 'social media', 'summaries'],
+        trendingRank: null,
+        upvotes: 4560,
+        uses: 180000
+    },
+
+    // Automation
+    {
+        id: 26,
+        name: 'Zapier',
+        description: 'Automation platform that connects apps and automates workflows without coding.',
+        category: 'automation',
+        pricing: 'Freemium',
+        features: ['App integration', 'Workflow automation', 'No-code', 'Triggers & actions'],
+        websiteUrl: 'https://zapier.com',
+        logoUrl: '⚙️',
+        rating: 4.5,
+        tags: ['workflow', 'integration', 'no-code', 'automation'],
+        trendingRank: null,
+        upvotes: 11200,
+        uses: 780000
+    },
+    {
+        id: 27,
+        name: 'UiPath',
+        description: 'Robotic Process Automation (RPA) platform with AI-powered automation capabilities.',
+        category: 'automation',
+        pricing: 'Paid',
+        features: ['RPA', 'Process mining', 'AI automation', 'Enterprise scale'],
+        websiteUrl: 'https://uipath.com',
+        logoUrl: '🤖',
+        rating: 4.3,
+        tags: ['RPA', 'enterprise', 'process mining', 'robotic'],
+        trendingRank: null,
+        upvotes: 5890,
+        uses: 420000
+    },
+    {
+        id: 28,
+        name: 'Make (Integromat)',
+        description: 'Visual automation platform that connects apps and automates workflows with advanced logic.',
+        category: 'automation',
+        pricing: 'Freemium',
+        features: ['Visual automation', 'Advanced logic', 'API integration', 'Real-time'],
+        websiteUrl: 'https://make.com',
+        logoUrl: '🔗',
+        rating: 4.4,
+        tags: ['visual', 'logic', 'API', 'real-time'],
+        trendingRank: null,
+        upvotes: 6730,
+        uses: 350000
+    },
+    {
+        id: 29,
+        name: 'Automation Anywhere',
+        description: 'Intelligent automation platform combining RPA with AI for business process automation.',
+        category: 'automation',
+        pricing: 'Paid',
+        features: ['Intelligent RPA', 'Business processes', 'AI integration', 'Analytics'],
+        websiteUrl: 'https://automationanywhere.com',
+        logoUrl: '🏢',
+        rating: 4.2,
+        tags: ['intelligent RPA', 'business', 'analytics', 'enterprise'],
+        trendingRank: null,
+        upvotes: 4120,
+        uses: 280000
+    },
+    {
+        id: 30,
+        name: 'n8n',
+        description: 'Open-source workflow automation tool that connects various services and automates tasks.',
+        category: 'automation',
+        pricing: 'Free',
+        features: ['Open source', 'Self-hosted', 'Visual workflows', 'Custom nodes'],
+        websiteUrl: 'https://n8n.io',
+        logoUrl: '🔄',
+        rating: 4.4,
+        tags: ['open source', 'self-hosted', 'workflows', 'custom'],
+        trendingRank: null,
+        upvotes: 3890,
+        uses: 150000
+    },
+
+    // Design & UI/UX
+    {
+        id: 31,
+        name: 'Figma AI',
+        description: 'AI-powered design features in Figma for automated layouts, content generation, and design assistance.',
+        category: 'design',
+        pricing: 'Freemium',
+        features: ['Auto layouts', 'Content generation', 'Design systems', 'Collaboration'],
+        websiteUrl: 'https://figma.com',
+        logoUrl: '🎨',
+        rating: 4.7,
+        tags: ['UI design', 'collaboration', 'layouts', 'design systems'],
+        trendingRank: null,
+        upvotes: 12500,
+        uses: 890000
+    },
+    {
+        id: 32,
+        name: 'Canva AI',
+        description: 'AI design assistant in Canva that helps create graphics, presentations, and marketing materials.',
+        category: 'design',
+        pricing: 'Freemium',
+        features: ['Graphic design', 'Templates', 'Magic resize', 'Background remover'],
+        websiteUrl: 'https://canva.com',
+        logoUrl: '🖼️',
+        rating: 4.6,
+        tags: ['graphic design', 'templates', 'marketing', 'easy'],
+        trendingRank: null,
+        upvotes: 15600,
+        uses: 1200000
+    },
+    {
+        id: 33,
+        name: 'Framer AI',
+        description: 'AI website builder that creates responsive websites from text descriptions and design ideas.',
+        category: 'design',
+        pricing: 'Freemium',
+        features: ['Website builder', 'Responsive design', 'Text-to-website', 'Animations'],
+        websiteUrl: 'https://framer.com',
+        logoUrl: '🌐',
+        rating: 4.4,
+        tags: ['website builder', 'responsive', 'animations', 'no-code'],
+        trendingRank: 9,
+        upvotes: 6890,
+        uses: 340000
+    },
+    {
+        id: 34,
+        name: 'Uizard',
+        description: 'AI-powered design tool that transforms sketches and wireframes into digital designs.',
+        category: 'design',
+        pricing: 'Freemium',
+        features: ['Sketch-to-design', 'Wireframing', 'AI assistance', 'Prototyping'],
+        websiteUrl: 'https://uizard.io',
+        logoUrl: '✏️',
+        rating: 4.2,
+        tags: ['sketch-to-design', 'wireframing', 'prototyping', 'AI assistance'],
+        trendingRank: null,
+        upvotes: 3450,
+        uses: 140000
+    },
+    {
+        id: 35,
+        name: 'Khroma',
+        description: 'AI color tool that learns your preferences and generates infinite color palettes.',
+        category: 'design',
+        pricing: 'Free',
+        features: ['Color palettes', 'Preference learning', 'Infinite combinations', 'Accessibility'],
+        websiteUrl: 'https://khroma.co',
+        logoUrl: '🌈',
+        rating: 4.3,
+        tags: ['color palettes', 'preferences', 'accessibility', 'combinations'],
+        trendingRank: null,
+        upvotes: 2780,
+        uses: 120000
+    },
+
+    // Data & Analytics
+    {
+        id: 36,
+        name: 'DataRobot',
+        description: 'Enterprise AI platform for automated machine learning and predictive analytics.',
+        category: 'data',
+        pricing: 'Paid',
+        features: ['AutoML', 'Predictive analytics', 'Model deployment', 'Enterprise AI'],
+        websiteUrl: 'https://datarobot.com',
+        logoUrl: '📊',
+        rating: 4.4,
+        tags: ['AutoML', 'enterprise', 'predictive', 'deployment'],
+        trendingRank: null,
+        upvotes: 5670,
+        uses: 280000
+    },
+    {
+        id: 37,
+        name: 'Tableau AI',
+        description: 'AI-powered data visualization and business intelligence with natural language queries.',
+        category: 'data',
+        pricing: 'Paid',
+        features: ['Data visualization', 'Natural language', 'Business intelligence', 'Dashboards'],
+        websiteUrl: 'https://tableau.com',
+        logoUrl: '📈',
+        rating: 4.5,
+        tags: ['visualization', 'BI', 'dashboards', 'natural language'],
+        trendingRank: null,
+        upvotes: 8920,
+        uses: 650000
+    },
+    {
+        id: 38,
+        name: 'Julius AI',
+        description: 'AI data analyst that helps you analyze data and create visualizations through conversation.',
+        category: 'data',
+        pricing: 'Freemium',
+        features: ['Conversational analysis', 'Data visualization', 'Python code', 'Charts & graphs'],
+        websiteUrl: 'https://julius.ai',
+        logoUrl: '🔍',
+        rating: 4.3,
+        tags: ['conversational', 'analysis', 'python', 'visualization'],
+        trendingRank: 10,
+        upvotes: 4230,
+        uses: 180000
+    },
+    {
+        id: 39,
+        name: 'MonkeyLearn',
+        description: 'Text analysis platform with AI models for sentiment analysis, keyword extraction, and more.',
+        category: 'data',
+        pricing: 'Freemium',
+        features: ['Text analysis', 'Sentiment analysis', 'Keyword extraction', 'Custom models'],
+        websiteUrl: 'https://monkeylearn.com',
+        logoUrl: '🐒',
+        rating: 4.2,
+        tags: ['text analysis', 'sentiment', 'keywords', 'custom models'],
+        trendingRank: null,
+        upvotes: 3560,
+        uses: 160000
+    },
+    {
+        id: 40,
+        name: 'Databricks AI',
+        description: 'Unified analytics platform for big data and machine learning with AI capabilities.',
+        category: 'data',
+        pricing: 'Paid',
+        features: ['Big data', 'Machine learning', 'Unified platform', 'Collaborative'],
+        websiteUrl: 'https://databricks.com',
+        logoUrl: '🧱',
+        rating: 4.4,
+        tags: ['big data', 'ML platform', 'collaborative', 'unified'],
+        trendingRank: null,
+        upvotes: 6780,
+        uses: 420000
+    },
+
+    // Productivity
+    {
+        id: 41,
+        name: 'Otter.ai',
+        description: 'AI meeting assistant that records, transcribes, and summarizes meetings automatically.',
+        category: 'productivity',
+        pricing: 'Freemium',
+        features: ['Meeting transcription', 'AI summaries', 'Action items', 'Integration'],
+        websiteUrl: 'https://otter.ai',
+        logoUrl: '🦦',
+        rating: 4.5,
+        tags: ['meetings', 'transcription', 'summaries', 'action items'],
+        trendingRank: null,
+        upvotes: 9340,
+        uses: 580000
+    },
+    {
+        id: 42,
+        name: 'Clockify AI',
+        description: 'AI-powered time tracking and productivity analytics for teams and individuals.',
+        category: 'productivity',
+        pricing: 'Freemium',
+        features: ['Time tracking', 'Productivity analytics', 'Team insights', 'Reporting'],
+        websiteUrl: 'https://clockify.me',
+        logoUrl: '⏰',
+        rating: 4.3,
+        tags: ['time tracking', 'analytics', 'productivity', 'reporting'],
+        trendingRank: null,
+        upvotes: 5420,
+        uses: 340000
+    },
+    {
+        id: 43,
+        name: 'Calendly AI',
+        description: 'AI scheduling assistant that optimizes meeting scheduling and calendar management.',
+        category: 'productivity',
+        pricing: 'Freemium',
+        features: ['Smart scheduling', 'Calendar optimization', 'Meeting insights', 'Automation'],
+        websiteUrl: 'https://calendly.com',
+        logoUrl: '📅',
+        rating: 4.6,
+        tags: ['scheduling', 'calendar', 'optimization', 'automation'],
+        trendingRank: null,
+        upvotes: 8760,
+        uses: 720000
+    },
+    {
+        id: 44,
+        name: 'Reclaim AI',
+        description: 'AI calendar assistant that automatically schedules your priorities and defends focus time.',
+        category: 'productivity',
+        pricing: 'Freemium',
+        features: ['Smart scheduling', 'Focus time', 'Priority management', 'Analytics'],
+        websiteUrl: 'https://reclaim.ai',
+        logoUrl: '🛡️',
+        rating: 4.4,
+        tags: ['focus time', 'priorities', 'smart scheduling', 'analytics'],
+        trendingRank: null,
+        upvotes: 4890,
+        uses: 230000
+    },
+    {
+        id: 45,
+        name: 'Motion',
+        description: 'AI productivity app that automatically plans your day, manages tasks, and schedules meetings.',
+        category: 'productivity',
+        pricing: 'Paid',
+        features: ['Automatic planning', 'Task management', 'Calendar integration', 'AI scheduling'],
+        websiteUrl: 'https://usemotion.com',
+        logoUrl: '⚡',
+        rating: 4.2,
+        tags: ['automatic planning', 'task management', 'AI scheduling', 'productivity'],
+        trendingRank: null,
+        upvotes: 3670,
+        uses: 180000
+    },
+
+    // Marketing & SEO
+    {
+        id: 46,
+        name: 'Surfer SEO',
+        description: 'AI-powered SEO tool that helps optimize content for search engines with data-driven insights.',
+        category: 'marketing',
+        pricing: 'Paid',
+        features: ['Content optimization', 'SERP analysis', 'Keyword research', 'Content editor'],
+        websiteUrl: 'https://surferseo.com',
+        logoUrl: '🏄',
+        rating: 4.5,
+        tags: ['SEO', 'content optimization', 'SERP analysis', 'keywords'],
+        trendingRank: null,
+        upvotes: 7230,
+        uses: 420000
+    },
+    {
+        id: 47,
+        name: 'MarketMuse',
+        description: 'AI content planning and optimization platform for SEO and content marketing.',
+        category: 'marketing',
+        pricing: 'Paid',
+        features: ['Content planning', 'Topic modeling', 'Competitive analysis', 'Content optimization'],
+        websiteUrl: 'https://marketmuse.com',
+        logoUrl: '🎯',
+        rating: 4.3,
+        tags: ['content planning', 'topic modeling', 'competitive analysis', 'SEO'],
+        trendingRank: null,
+        upvotes: 4560,
+        uses: 240000
+    },
+    {
+        id: 48,
+        name: 'Persado',
+        description: 'AI platform that generates marketing language and measures emotional impact.',
+        category: 'marketing',
+        pricing: 'Paid',
+        features: ['Marketing language', 'Emotional AI', 'A/B testing', 'Performance optimization'],
+        websiteUrl: 'https://persado.com',
+        logoUrl: '💭',
+        rating: 4.2,
+        tags: ['marketing language', 'emotional AI', 'A/B testing', 'optimization'],
+        trendingRank: null,
+        upvotes: 3890,
+        uses: 150000
+    },
+    {
+        id: 49,
+        name: 'Phrasee',
+        description: 'AI copywriting platform that generates and optimizes marketing copy for emails and ads.',
+        category: 'marketing',
+        pricing: 'Paid',
+        features: ['Email copy', 'Ad copy', 'Brand voice', 'Performance tracking'],
+        websiteUrl: 'https://phrasee.co',
+        logoUrl: '✉️',
+        rating: 4.1,
+        tags: ['email copy', 'ad copy', 'brand voice', 'performance'],
+        trendingRank: null,
+        upvotes: 2890,
+        uses: 120000
+    },
+    {
+        id: 50,
+        name: 'Frase',
+        description: 'AI SEO content tool that helps research, write, and optimize content for search engines.',
+        category: 'marketing',
+        pricing: 'Freemium',
+        features: ['Content research', 'SEO writing', 'SERP analysis', 'Content briefs'],
+        websiteUrl: 'https://frase.io',
+        logoUrl: '📝',
+        rating: 4.4,
+        tags: ['content research', 'SEO writing', 'SERP', 'briefs'],
+        trendingRank: null,
+        upvotes: 5670,
+        uses: 310000
+    },
+
+    // Research & Knowledge
+    {
+        id: 51,
+        name: 'Perplexity AI',
+        description: 'AI-powered research assistant that provides accurate answers with sources and citations.',
+        category: 'research',
+        pricing: 'Freemium',
+        features: ['Research assistance', 'Source citations', 'Real-time info', 'Follow-up questions'],
+        websiteUrl: 'https://perplexity.ai',
+        logoUrl: '🔍',
+        rating: 4.6,
+        tags: ['research', 'citations', 'real-time', 'accuracy'],
+        trendingRank: null,
+        upvotes: 8940,
+        uses: 480000
+    },
+    {
+        id: 52,
+        name: 'Consensus',
+        description: 'AI research tool that searches scientific papers and provides evidence-based answers.',
+        category: 'research',
+        pricing: 'Freemium',
+        features: ['Scientific papers', 'Evidence-based', 'Research synthesis', 'Academic sources'],
+        websiteUrl: 'https://consensus.app',
+        logoUrl: '🧪',
+        rating: 4.4,
+        tags: ['scientific papers', 'evidence-based', 'academic', 'research'],
+        trendingRank: null,
+        upvotes: 4230,
+        uses: 190000
+    },
+
+    // Education & Learning
+    {
+        id: 53,
+        name: 'Khan Academy AI',
+        description: 'AI tutor that provides personalized learning assistance and educational support.',
+        category: 'education',
+        pricing: 'Free',
+        features: ['Personalized tutoring', 'Educational support', 'Multiple subjects', 'Progress tracking'],
+        websiteUrl: 'https://khanacademy.org',
+        logoUrl: '🎓',
+        rating: 4.7,
+        tags: ['tutoring', 'personalized', 'education', 'progress tracking'],
+        trendingRank: null,
+        upvotes: 11200,
+        uses: 850000
+    },
+    {
+        id: 54,
+        name: 'Socratic by Google',
+        description: 'AI homework helper that uses camera to scan problems and provides step-by-step solutions.',
+        category: 'education',
+        pricing: 'Free',
+        features: ['Homework help', 'Camera scanning', 'Step-by-step', 'Multiple subjects'],
+        websiteUrl: 'https://socratic.org',
+        logoUrl: '📱',
+        rating: 4.5,
+        tags: ['homework help', 'scanning', 'step-by-step', 'mobile'],
+        trendingRank: null,
+        upvotes: 9560,
+        uses: 620000
+    },
+    {
+        id: 55,
+        name: 'Duolingo AI',
+        description: 'AI-powered language learning platform with personalized lessons and conversation practice.',
+        category: 'education',
+        pricing: 'Freemium',
+        features: ['Language learning', 'Personalized lessons', 'Conversation practice', 'Progress tracking'],
+        websiteUrl: 'https://duolingo.com',
+        logoUrl: '🦜',
+        rating: 4.6,
+        tags: ['language learning', 'personalized', 'conversation', 'mobile'],
+        trendingRank: null,
+        upvotes: 13400,
+        uses: 1100000
+    }
+];
+
+// Export data for use in main.js
+window.aiToolsData = {
+    categories,
+    tools: aiTools
+};
